title: HAPI Docs
description: Internal documentation for the CSU Human-Aware Planning and Interaction (HAPI) Lab
theme: just-the-docs

url: https://kickblip.github.io/hapidocs

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/kickblip/hapidocs
